<?php get_header();
	
						$post_type = get_post_type();
					    
						if ( $post_type == "article_ae" ) {
							$cat_id     = 4;
						} elseif ( $post_type == "article_sports" ) {
							$cat_id     = 10;
						} elseif ( $post_type == "article_living" ) {
							$cat_id     = 11;
						} elseif ( $post_type == "article_ae" ) {
							$cat_id     = 2341;
						} elseif ( $post_type == "article_opinion" ) {
							$cat_id     = 5;
						} elseif ( $post_type == "multimedia" ) {
							$cat_id     = 194;
						} elseif ( $post_type == "slideshows" ) {
							$cat_id     = 39;
						}
						
?>
			
			<div id="content">
			
				<div id="inner-content" class="wrap clearfix">
				
				    <div id="main" class="twelvecol first clearfix" role="main">
				    
				    <h1 class="archive-main-title" class="first last twelvecol"><?php post_type_archive_title(); ?>
								<?php if ( is_post_type_archive() ) : ?>
									<span class="archive-breadcrumb"><?php
										if ( is_year() || is_day() || is_month() ) { ?>
											 / archive / <?php the_time('Y'); }
											if ( is_day() || is_month() ) { ?>
												 / <?php the_time('F'); } 
												if ( is_day() ) { ?>
													 / <?php the_time('d'); } ?></span>
								<?php endif; ?>
					</h1>
						
								<?php // no reason to change this stuff
								$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
								$cat_link = get_category_link($cat_id);
								$top_article_class = 'top-' . $post_type;
								
								// set class to first or last depending on position in three column layout
								// http://wordpress.org/support/topic/adding-different-styling-every-3rd-post
								$style_classes = array('first', '', 'last');
								$styles_count = count($style_classes);
								$style_index = 0;
								
								// sets up counter to display first post differently (see TOP ARTICLE)
								$firstpost = 'firstpost'; ?>
						
						<?php
						if ( !is_paged() ) { ?>
							
								
								<div id="multimedia-mgallery" class="mgallery ninecol last clearfix">
								
									<div id="post-type-loop-top" class="multimedia-mgallery-top article-container twelvecol first last clearfix">
							
										<?php // begin the loop, generated by the gd cpt plugin
										if (have_posts()) : while (have_posts()) : the_post();
									
										if ( $firstpost == 'firstpost' ) { ?>
								
											<?php $firstpost = ''; ?>
								
											<article id="post-<?php the_ID(); ?>" <?php post_class( 'top-multimedia-article clearfix' ); ?> role="article">
												
												<?php
												// http://designisphilosophy.com/tutorials/simple-video-embedding-with-custom-fields-in-wordpress-youtube/				
												// Get the video URL and put it in the $video variable
												$videoID = get_post_meta($post->ID, 'video_link', true);
												// Check if there is in fact a video URL
												if ($videoID) {
													echo '<div class="video-container clearfix">';
													// Echo the embed code via oEmbed
													echo wp_oembed_get( $videoID ); 
													echo '</div>';
												} ?>
		
												<header class="clearfix">
													<div class="post-category-list-container"><?php // the_category_but( $cat_id ); ?></div>
													<h2 class="multimedia-headline multimedia-top-headline headline top-headline"><a href="<?php the_permalink() ?>" rel="bookmark" title="<?php the_title_attribute(); ?>"><?php the_title(); ?></a></h2>
													<p class="multimedia-byline byline"><?php _e("by", "zombietheme"); ?> <span class="multimedia-authors authors"><?php if(function_exists('coauthors_posts_links')) coauthors_posts_links(); else the_author_posts_link(); ?></span></p><p><time class="sc" datetime="<?php echo the_time('c'); ?>" pubdate><?php echo ttn_article_published_link(); ?></time></p>
												</header>
		
												<section class="multimedia-summary media-summary clearfix">
													<?php echo get_post_meta($post->ID, 'media_summary', true); ?>
												</section> <!-- end multimedia-dek -->
		
											</article> <!-- end article -->
		
										<?php } // end first post
								
										endwhile; endif; // close loop
								
										rewind_posts(); // start the loop over again ?>
									
									</div> <!-- end #post-type-loop-top -->
								
								
									<div id="post-type-loop-main" class="twelvecol first last clearfix">
					
										<?php // begin the loop again
								
										$firstpost = 'firstpost';
								
										if (have_posts()) : while (have_posts()) : the_post();
								
										if ( $firstpost == 'firstpost' ) {
											$firstpost = '';
										} 
								
										else { // all non-first posts format ?>
												
												<?php 
												// this is the second part of the operation that determines first or last class based on column divisions. see above.
												$k = $style_classes[$style_index++ % $styles_count]; ?>
												
												<div class="article-container fourcol clearfix <?php echo $k ?>">
		
													<article id="post-<?php the_ID(); ?>" <?php post_class(); ?> role="article">
														<a href="<?php the_permalink(); ?>" class="article-link">
														
															<?php if ( has_post_thumbnail() ) : ?>
																<div class="video-thumbnail-container">
																	<?php the_post_thumbnail('zom-landscape-396'); ?>
																</div>
															<?php endif; ?>
						
															<header>
																<div class="post-category-list-container"><?php // the_category_but( $cat_id ); ?></div>
																<h2 class="multimedia-headline headline"><?php the_title(); ?></h2>
																<p class="multimedia-byline byline"><i><?php _e("by", "zombietheme"); ?></i> <span class="multimedia-authors authors"><?php if(function_exists('coauthors')) coauthors(); else the_author(); ?></span></p><p><time class="sc" datetime="<?php echo the_time('c'); ?>" pubdate><?php echo get_the_time( 'd F Y' ); ?></time></p>
															</header>
						
															<section class="multimedia-dek dek">
																<?php echo get_post_meta($post->ID, 'media_dek', true); ?>
															</section> <!-- end multimedia-dek -->
														
														</a> <!-- end article-link -->
					
													</article> <!-- end article -->
												
												</div> <!-- end article-container -->
								
										<?php } // end non-first posts
							
										endwhile; // close while_posts() loop but continue past the pagination area to see the real end
								
										if (function_exists('bones_page_navi')) { // if experimental feature is active 
		
												bones_page_navi(); // use the page navi function 
				
											} else { // if it is disabled, display regular wp prev & next links ?>
												<nav class="wp-prev-next">
													<ul class="clearfix">
														<li class="prev-link"><?php next_posts_link(_e('&laquo; Older Entries', "zombietheme")) ?></li>
														<li class="next-link"><?php previous_posts_link(_e('Newer Entries &raquo;', "zombietheme")) ?></li>
													</ul>
												</nav>
										<?php } ?>
									
										<?php else : // if the loop returns nothing ?>
							
											<article id="post-not-found" class="hentry clearfix">
												<header class="article-header">
													<h1><?php _e("Oops, Post Not Found!", "bonestheme"); ?></h1>
												</header>
												<section class="post-content">
													<p><?php _e("Uh Oh. Something is missing. Try double checking things.", "bonestheme"); ?></p>
												</section>
												<footer class="article-footer">
													<p><?php _e("This is the error message in the custom posty type archive template.", "bonestheme"); ?></p>
												</footer>
											</article>
							
										<?php endif; // kill loop ?>
									
							
									</div> <!-- end #post-type-loop-main -->
								
								</div> <!-- end #multimedia-mgallery -->
								
								<aside id="multimedia-aside" class="threecol first">
							
								
							
								</aside>								
							
						<?php } // end if !is_paged() ?>
						
						
						
						
						
						<?php if ( is_paged() ){ ?>
						
								
						
						
								<div id="multimedia-mgallery" class="mgallery ninecol last clearfix">
							
									<div id="post-type-loop-main" class="twelvecol first last clearfix">
					
										<?php // begin the loop again
								
										if (have_posts()) : while (have_posts()) : the_post(); ?>
										
												<?php 
												// this is the second part of the operation that determines first or last class based on column divisions. see above.
												$k = $style_classes[$style_index++ % $styles_count]; ?>
										
												<div class="article-container fourcol clearfix <?php echo $k ?>">
		
													<article id="post-<?php the_ID(); ?>" <?php post_class(); ?> role="article">
													
														<a href="<?php the_permalink(); ?>" class="article-link">
					
															<?php if ( has_post_thumbnail() ) : ?>
						
																<div class="multimedia-thumb mgallery-thumb">
																	<?php the_post_thumbnail('zom-landscape-396'); ?>
																</div>
						
															<?php endif; ?>
						
															<header>
																<div class="post-category-list-container"><?php // the_category_but( $cat_id ); ?></div>
																<h2 class="multimedia-headline headline"><?php the_title(); ?></h2>
																<p class="multimedia-byline byline"><i><?php _e("by", "zombietheme"); ?></i> <span class="multimedia-authors authors"><?php if(function_exists('coauthors')) coauthors(); else the_author(); ?></span></p><p><time class="sc" datetime="<?php echo the_time('c'); ?>" pubdate><?php echo get_the_time( 'd F Y' ); ?></time></p>
															</header>
						
															<section class="multimedia-dek dek">
																<?php get_post_meta($post->ID, 'media_summary', true); ?>
															</section> <!-- end multimedia-dek -->
														
														</a> <!-- end article-link -->
					
													</article> <!-- end article -->
												
												</div> <!-- end article-container -->
								
										<?php endwhile; // close while_posts() loop but continue past the pagination area to see the real end
								
										if (function_exists('bones_page_navi')) { // if experimental feature is active 
		
												bones_page_navi(); // use the page navi function 
				
											} else { // if it is disabled, display regular wp prev & next links ?>
												<nav class="wp-prev-next">
													<ul class="clearfix">
														<li class="prev-link"><?php next_posts_link(_e('&laquo; Older Entries', "zombietheme")) ?></li>
														<li class="next-link"><?php previous_posts_link(_e('Newer Entries &raquo;', "zombietheme")) ?></li>
													</ul>
												</nav>
										<?php } ?>
									
										<?php else : // if the loop returns nothing ?>
							
											<article id="post-not-found" class="hentry clearfix">
												<header class="article-header">
													<h1><?php _e("Oops, Post Not Found!", "bonestheme"); ?></h1>
												</header>
												<section class="post-content">
													<p><?php _e("Uh Oh. Something is missing. Try double checking things.", "bonestheme"); ?></p>
												</section>
												<footer class="article-footer">
													<p><?php _e("This is the error message in the custom posty type archive template.", "bonestheme"); ?></p>
												</footer>
											</article>
							
										<?php endif; // kill loop ?>
									
							
									</div> <!-- end #post-type-loop-main -->
								
								</div> <!-- end #multimedia-mgallery -->
							
							
						<?php } // end if is_paged() ?>
						
    				</div> <!-- end #main -->
                
                </div> <!-- end #inner-content -->
                
			</div> <!-- end #content -->

<?php get_footer(); ?>